library("scales")
library("ggplot2")
library("dplyr")
library("tidyr")
library("RColorBrewer")

#library("XLConnect")
library("cellranger")
library("readxl")
library("xtable")
library("matlib")
#install.packages("rJava")
#install.packages("XLConnectJars")
#install.packages("XLConnect")

library(quadprog)
library(optiSolve)
