
############################################
############ Construct IOT with variable coal share in generation mix. 
####################### Version 1, based on Eskom's integrated report 2014/15, Operating cost data, page 91. 
############################################

## Share operating cost coal, as from Integrated report :
n <- 50
mu <- 51554/(51554 + 530 + 9546 + 9453) # from Eskom integrated report 2014/15, primary energy expenses
sector.mod <- "I33"

## Inputs for elec generation through coal

sector.list <- df.IOT2014$Description[1:50]

input.coal  <- c("Coal and lignite","Transport","Coke oven manufacture")

#input.other <- c("Nuclear fuel","Electricity, gas and water","Basic iron and steel","Structural metal","General machinery")
input.other <- c("Nuclear fuel","Basic iron and steel","Structural metal","General machinery")

input.cost  <- sector.list[! sector.list %in% c(input.coal,input.other)]

input.total.cost <- sum(df.IOT2014[df.IOT2014$Description %in% sector.list,"I33"])
input.coal.cost  <- sum(df.IOT2014[df.IOT2014$Description %in% input.coal,"I33"])
input.other.cost <- sum(df.IOT2014[df.IOT2014$Description %in% input.other,"I33"])
input.cost.cost  <- sum(df.IOT2014[df.IOT2014$Description %in% input.cost,"I33"])

## Construct new input column, assuming all elec gas and water to buying from IPPs

mu.bis <- (mu * input.total.cost - input.coal.cost ) / input.cost.cost

coalWh.otherWh  <- 9    # proportion in MWh generated by coal versus other generation technos, 90% coal, 10% others

lambda.c          <- -0.10 # coal decrease with (1 + lambda),
lambda.o          <- -lambda.c * coalWh.otherWh 

newTechno <- data.frame(sector.list)
newTechno$val <- rep(0,n)
colnames(newTechno) <- c("Description", sector.mod)

newTechno[newTechno$Description %in% input.coal, sector.mod] <- (1 + lambda.c) * df.IOT2014[df.IOT2014$Description %in% input.coal,"I33"]
newTechno[newTechno$Description %in% input.other, sector.mod] <- (1 + lambda.o) * df.IOT2014[df.IOT2014$Description %in% input.other,"I33"]

newTechno[newTechno$Description %in% input.cost, sector.mod] <- 
  (1 + lambda.c) * mu.bis * df.IOT2014[df.IOT2014$Description %in% input.cost,"I33"] +
  (1 + lambda.o) * (1-mu.bis) * df.IOT2014[df.IOT2014$Description %in% input.cost,"I33"]

## Construct new input column, assuming buying from IPPs disappears as revenue-expense within I33 to I33.
## Instead, assume slightly larger share than mu of input.cost is spent on other technos

